/* js/creatures/wolf.js
 * Criatura COMPLETA: Lobo (predador). Tudo que define o lobo fica neste arquivo.
 * Depende de registry.js (carregar depois dele). Ordem de carga: rabbit.js, wolf.js, deer.js
 * (a ordem define a prioridade de deteccao por nome: coelho > lobo > cervo).
 *
 * Dois nascimentos: `spawn` (Lobo dos Bosques, florestas) e `spawnVariants.snow` (Lobo das Neves, biomas de neve/gelo).
 * `behavior.predator`: presas fogem dele (updatePreyAI). `behavior.hunter`: numeros da IA de caca
 * (creatures-manager.js): cacar presas num raio, perseguir, atacar e vagar quando nao ha presa.
 */
"use strict";
CREATURES.wolf = {
  id: "wolf",
  // Nascimento no mundo (valores do spawn)
  spawn: { name: "Lobo dos Bosques", color: "#475569", accentColor: "#f59e0b", hp: 24, attack: 6, speed: 1.05, scale: 0.95 },
  spawnVariants: {
    snow: { name: "Lobo das Neves", color: "#94a3b8", accentColor: "#38bdf8", hp: 25, attack: 6, speed: 1.1, scale: 1 },
  },
  // Comportamento: predador (as presas fogem dele); particulas ao morrer
  behavior: {
    prey: false,
    predator: true,
    deathParticles: 12,
    // Nome da ameaca mostrado/guardado nas presas (threatName)
    threatName: "lobo",
    // Recarga do ataque ao jogador (s)
    attackCooldown: 1,
    // Valores usados pela IA de caca (creatures-manager.js)
    hunter: {
      huntRadius: 185,
      meleeRange: 22,
      huntSpeedMult: 1.35,
      attackCooldownPrey: 1.1,
      wanderWait: [1.8, 2.5],
      idleChance: 0.3,
      wanderSpeedMult: 0.6,
    },
  },
  // Carcaca deixada ao morrer
  carcass: {
    name: "Carcaça de Lobo",
    bodyName: "Corpo de Lobo",
    description: "Corpo de lobo abatido. Pode ser destrinchado com uma faca para extrair ossos, pele, carne, entranhas e dente de lobo.",
  },
  // Ficha mostrada ao destrinchar
  sheet: {
          name: "Lobo Selvagem",
          species: "Canídeo Predador",
          icon: "🐺",
          badgeColor: "text-slate-300 border-slate-500/40 bg-slate-900/60",
          description:
            "Predador canino ágil das estepes e bosques nevados. Rende pele espessa, carne, ossos, entranhas e dentes afiados.",
          exclusiveNote:
            "Item Exclusivo: Dente de Lobo (material para armas perfurantes e talismãs).",
        },
  // Como reconhecer um item/carcaca desta criatura (t = nome, l = id, o = icone, tudo minusculo)
  detect: (t, l, o) => t.includes("lobo") || t.includes("wolf") || l.includes("wolf") || l.includes("lobo") || o === "creature_wolf",
  // Reconhecer por nome/id/icone para escolher o DESENHO do icone (antigo lb). t=nome, l=id, o=icone (minusculos)
  detectIcon: (t, l, o) => o === "creature_wolf" || o === "wolf" || t.includes("lobo") || l.includes("wolf"),
  // Despojos ao destrinchar (t = timestamp, l = gerador de sufixo aleatorio)
  loot: (t, l) => [
          {
            id: `butcher_wolf_bone_${t}_${l()}`,
            isExclusive: !1,
            status: "pending",
            item: {
              isCreaturePart: !0,
              id: `item_osso_lobo_${t}_${l()}`,
              name: "Ossos de Lobo",
              categoryType: "material",
              rarity: "comum",
              stackCount: 3,
              isEquippable: !1,
              icon: "bone",
              color: "#e2e8f0",
              value: 12,
              description:
                "Ossos densos e resistentes de predador canino. Matéria-prima clássica para ferramentas, agulhas e entalhes.",
            },
          },
          {
            id: `butcher_wolf_pelt_${t}_${l()}`,
            isExclusive: !1,
            status: "pending",
            item: {
              isCreaturePart: !0,
              id: `item_pele_lobo_${t}_${l()}`,
              name: "Pele de Lobo",
              categoryType: "material",
              rarity: "incomum",
              stackCount: 1,
              isEquippable: !1,
              icon: "shirt",
              color: "#94a3b8",
              value: 30,
              description:
                "Couro felpudo com espessa camada térmica de lã de lobo. Ideal para confecção de mantos e reforço de armaduras.",
            },
          },
          {
            id: `butcher_wolf_meat_${t}_${l()}`,
            isExclusive: !1,
            status: "pending",
            item: {
              isCreaturePart: !0,
              id: `item_carne_lobo_${t}_${l()}`,
              name: "Carne de Lobo Crua",
              categoryType: "consumable",
              rarity: "comum",
              stackCount: 2,
              isEquippable: !1,
              icon: "utensils",
              color: "#f87171",
              value: 18,
              description:
                "Carne crua de caça. Pode ser consumida (+25 Vida, +30 Stamina) ou levada à fogueira e forno de barro para assar.",
            },
          },
          {
            id: `butcher_wolf_guts_${t}_${l()}`,
            isExclusive: !1,
            status: "pending",
            item: {
              isCreaturePart: !0,
              id: `item_entranhas_lobo_${t}_${l()}`,
              name: "Entranhas de Lobo",
              categoryType: "material",
              rarity: "comum",
              stackCount: 1,
              isEquippable: !1,
              icon: "heart",
              color: "#991b1b",
              value: 14,
              description:
                "Vísceras frescas colhidas durante a evisceração. Essenciais para compostos químicos, iscas e fermentações.",
            },
          },
          {
            id: `butcher_wolf_tooth_${t}_${l()}`,
            isExclusive: !0,
            exclusiveLabel: "⭐ Exclusivo de Lobo",
            status: "pending",
            item: {
              isCreaturePart: !0,
              id: `item_dente_lobo_${t}_${l()}`,
              name: "Dente de Lobo Alfa",
              categoryType: "material",
              rarity: "raro",
              stackCount: 2,
              isEquippable: !1,
              icon: "sparkles",
              color: "#f1f5f9",
              value: 48,
              description:
                "Presa afiada e curva do lobo predador. Item exclusivo valioso, cobiçado para ornamentos cerimoniais e armas perfurantes.",
            },
          },
        ],
  // Desenho no Canvas (codigo movido sem alteracoes dos arquivos de engine)
  draw: {
    // Corpo vivo no mundo (antigo ramo final de Eg). Tambem e o desenho usado por tipos sem desenho proprio.
    body: function (e, t, o, l) {
      e.save();
      const u = t.facing === "left" ? -1 : 1;
      e.scale(u, 1);
      const m = l ? "#ffffff" : t.color,
        c = l ? "#e2e8f0" : "#475569",
        f = l ? "#ffffff" : "#cbd5e1",
        g = l ? "#ffffff" : "#e2e8f0",
        w = t.vx * t.vx + t.vy * t.vy > 0.04,
        v = w ? t.animTimer * 9 : t.animTimer * 2.2,
        T = w
          ? Math.sin(v * 2) * 1.5 * o
          : Math.sin(t.animTimer * 2.5) * 0.6 * o,
        S = Math.sin(t.animTimer * 3) * 0.4 * o,
        p = w ? Math.sin(v) * 4.2 * o : 0,
        j = w ? Math.sin(v + Math.PI) * 4.2 * o : 0,
        P = w ? Math.sin(v + Math.PI * 0.7) * 4.2 * o : 0,
        A = w ? Math.sin(v + Math.PI * 1.7) * 4.2 * o : 0;
      ((e.fillStyle = c),
        e.beginPath(),
        e.moveTo(-6 * o, -6 * o + T),
        e.lineTo(-8 * o + A, -1 * o + T),
        e.lineTo(-7 * o + A, 2 * o),
        e.lineTo(-4 * o + A, 2 * o),
        e.lineTo(-4 * o, -6 * o + T),
        e.closePath(),
        e.fill(),
        e.beginPath(),
        e.moveTo(5 * o, -7 * o + T),
        e.lineTo(6 * o + j, -1 * o + T),
        e.lineTo(7 * o + j, 2 * o),
        e.lineTo(4 * o + j, 2 * o),
        e.lineTo(3 * o, -7 * o + T),
        e.closePath(),
        e.fill());
      const x = Math.sin(v * 1.2) * 2.5 * o;
      ((e.strokeStyle = m),
        (e.lineWidth = 3.6 * o),
        (e.lineCap = "round"),
        e.beginPath(),
        e.moveTo(-9 * o, -8 * o + T),
        e.quadraticCurveTo(-14 * o, -11 * o + x, -13 * o, -4 * o + x),
        e.stroke(),
        (e.strokeStyle = f),
        (e.lineWidth = 2.2 * o),
        e.beginPath(),
        e.moveTo(-14 * o, -7 * o + x),
        e.lineTo(-13 * o, -4 * o + x),
        e.stroke(),
        (e.fillStyle = m),
        e.beginPath(),
        e.moveTo(-9 * o, -10 * o + T),
        e.quadraticCurveTo(-2 * o, -13 * o + T, 4 * o, -12 * o + T),
        e.lineTo(7 * o, -10 * o + T),
        e.quadraticCurveTo(8 * o, -4 * o + T + S, 4 * o, -2 * o + T + S),
        e.quadraticCurveTo(-3 * o, -4 * o + T, -8 * o, -6 * o + T),
        e.closePath(),
        e.fill(),
        l ||
          ((e.fillStyle = g),
          e.beginPath(),
          e.moveTo(2 * o, -9 * o + T),
          e.quadraticCurveTo(7 * o, -5 * o + T, 5 * o, -2 * o + T + S),
          e.quadraticCurveTo(1 * o, -3 * o + T, -2 * o, -5 * o + T),
          e.closePath(),
          e.fill(),
          (e.fillStyle = f),
          e.beginPath(),
          e.moveTo(6 * o, -9 * o + T),
          e.lineTo(9.2 * o, -6 * o + T),
          e.lineTo(7.2 * o, -4 * o + T),
          e.lineTo(9.8 * o, -2 * o + T),
          e.lineTo(6.2 * o, -1 * o + T),
          e.closePath(),
          e.fill()),
        (e.fillStyle = m),
        e.beginPath(),
        e.moveTo(-5 * o, -10 * o + T),
        e.quadraticCurveTo(-9 * o, -5 * o + T, -7 * o + P, 0 * o + T),
        e.lineTo(-6 * o + P, 3 * o),
        e.lineTo(-3 * o + P, 3 * o),
        e.lineTo(-3.5 * o + P, 0 * o + T),
        e.quadraticCurveTo(-3 * o, -6 * o + T, -3 * o, -8 * o + T),
        e.closePath(),
        e.fill(),
        e.beginPath(),
        e.moveTo(4 * o, -10 * o + T),
        e.lineTo(6 * o + p, 0 * o + T),
        e.lineTo(6.5 * o + p, 3 * o),
        e.lineTo(3.5 * o + p, 3 * o),
        e.lineTo(3 * o + p, 0 * o + T),
        e.lineTo(1.5 * o, -8 * o + T),
        e.closePath(),
        e.fill(),
        (e.fillStyle = "#0f172a"),
        e.fillRect(-6 * o + P, 2.5 * o, 3.2 * o, 0.9 * o),
        e.fillRect(3.5 * o + p, 2.5 * o, 3.2 * o, 0.9 * o));
      const M = 7 * o,
        $ = -12 * o + T;
      if (
        ((e.fillStyle = m),
        e.beginPath(),
        e.moveTo(3 * o, -12 * o + T),
        e.lineTo(M + 2 * o, $ - 4 * o),
        e.lineTo(M + 5 * o, $),
        e.lineTo(5 * o, -7 * o + T),
        e.closePath(),
        e.fill(),
        e.beginPath(),
        e.ellipse(
          M + 1.5 * o,
          $ - 1 * o,
          4.2 * o,
          3.8 * o,
          0.15,
          0,
          Math.PI * 2,
        ),
        e.fill(),
        e.beginPath(),
        e.moveTo(M + 3 * o, $ - 2.5 * o),
        e.lineTo(M + 8.5 * o, $ - 1 * o),
        e.lineTo(M + 8.5 * o, $ + 1.2 * o),
        e.lineTo(M + 4 * o, $ + 2.5 * o),
        e.closePath(),
        e.fill(),
        (e.fillStyle = l ? "#ffffff" : g),
        e.beginPath(),
        e.moveTo(M + 4 * o, $ + 1.5 * o),
        e.lineTo(M + 7.8 * o, $ + 1.2 * o),
        e.lineTo(M + 7 * o, $ + 2.5 * o),
        e.lineTo(M + 3.5 * o, $ + 2.8 * o),
        e.closePath(),
        e.fill(),
        (e.fillStyle = "#0f172a"),
        e.beginPath(),
        e.roundRect(M + 8 * o, $ - 1.5 * o, 1.6 * o, 1.8 * o, 0.4 * o),
        e.fill(),
        (e.fillStyle = "#ffffff"),
        e.beginPath(),
        e.moveTo(M + 6.8 * o, $ + 1.2 * o),
        e.lineTo(M + 7.4 * o, $ + 2.6 * o),
        e.lineTo(M + 7.9 * o, $ + 1.2 * o),
        e.closePath(),
        e.fill(),
        (e.fillStyle = c),
        e.beginPath(),
        e.moveTo(M - 0.5 * o, $ - 3.5 * o),
        e.lineTo(M + 0.5 * o, $ - 8.5 * o),
        e.lineTo(M + 2.8 * o, $ - 3.8 * o),
        e.closePath(),
        e.fill(),
        (e.fillStyle = m),
        e.beginPath(),
        e.moveTo(M + 1.2 * o, $ - 3.8 * o),
        e.lineTo(M + 2.8 * o, $ - 9.2 * o),
        e.lineTo(M + 5 * o, $ - 4 * o),
        e.closePath(),
        e.fill(),
        (e.fillStyle = l ? "#ffffff" : "#f43f5e"),
        e.beginPath(),
        e.moveTo(M + 2.1 * o, $ - 4.4 * o),
        e.lineTo(M + 3.1 * o, $ - 8.2 * o),
        e.lineTo(M + 4.2 * o, $ - 4.6 * o),
        e.closePath(),
        e.fill(),
        (e.fillStyle = "#0f172a"),
        e.beginPath(),
        e.ellipse(
          M + 4.2 * o,
          $ - 1.6 * o,
          1.8 * o,
          1.2 * o,
          0.1,
          0,
          Math.PI * 2,
        ),
        e.fill(),
        (e.fillStyle = l ? "#ef4444" : t.accentColor),
        e.beginPath(),
        e.arc(M + 4.4 * o, $ - 1.6 * o, 1.1 * o, 0, Math.PI * 2),
        e.fill(),
        (e.fillStyle = "#0f172a"),
        e.beginPath(),
        e.ellipse(
          M + 4.6 * o,
          $ - 1.6 * o,
          0.45 * o,
          0.9 * o,
          0,
          0,
          Math.PI * 2,
        ),
        e.fill(),
        (e.fillStyle = "#ffffff"),
        e.beginPath(),
        e.arc(M + 4.2 * o, $ - 2 * o, 0.4 * o, 0, Math.PI * 2),
        e.fill(),
        !l && t.accentColor === "#38bdf8")
      ) {
        const z = (t.animTimer * 2.8) % Math.PI;
        ((e.fillStyle = "rgba(224, 242, 254, 0.35)"),
          e.beginPath(),
          e.arc(
            M + 10 * o + Math.cos(z) * 2 * o,
            $ - 0.5 * o - Math.sin(z) * 1.5 * o,
            (1.2 + z * 0.8) * o,
            0,
            Math.PI * 2,
          ),
          e.fill());
      }
      e.restore();
    },
    // Carcaca no chao (antigo ramo wolf de Ag)
    carcass: function (e, t, o, u) {
        const m = t.color,
          c = "#334155",
          f = "#e2e8f0";
        ((e.fillStyle = `rgba(15, 23, 42, ${0.4 * u})`),
          e.beginPath(),
          e.ellipse(2 * o, 4 * o, 14 * o, 5 * o, 0, 0, Math.PI * 2),
          e.fill(),
          (e.strokeStyle = m),
          (e.lineWidth = 3.2 * o),
          (e.lineCap = "round"),
          e.beginPath(),
          e.moveTo(-9 * o, 1 * o),
          e.quadraticCurveTo(-14 * o, 3 * o, -12 * o, 7 * o),
          e.stroke(),
          (e.fillStyle = c),
          e.fillRect(-6 * o, 2 * o, 2.5 * o, 4 * o),
          e.fillRect(3.5 * o, 2 * o, 2.5 * o, 4 * o),
          (e.fillStyle = "#0f172a"),
          e.fillRect(-6 * o, 5.5 * o, 2.5 * o, 0.8 * o),
          e.fillRect(3.5 * o, 5.5 * o, 2.5 * o, 0.8 * o),
          (e.fillStyle = m),
          e.beginPath(),
          e.ellipse(0, 0, 11 * o, 5.5 * o, 0.05, 0, Math.PI * 2),
          e.fill(),
          (e.fillStyle = f),
          e.beginPath(),
          e.ellipse(2 * o, 1.5 * o, 7 * o, 2.8 * o, 0.05, 0, Math.PI * 2),
          e.fill(),
          (e.fillStyle = m),
          e.beginPath(),
          e.ellipse(8 * o, 1 * o, 5.5 * o, 4 * o, 0.12, 0, Math.PI * 2),
          e.fill(),
          e.beginPath(),
          e.moveTo(9 * o, -0.5 * o),
          e.lineTo(14 * o, 1.5 * o),
          e.lineTo(13.5 * o, 3.8 * o),
          e.lineTo(8 * o, 3.8 * o),
          e.closePath(),
          e.fill(),
          (e.fillStyle = "#0f172a"),
          e.fillRect(13.2 * o, 1 * o, 1.4 * o, 1.6 * o),
          (e.fillStyle = "#ffffff"),
          e.beginPath(),
          e.moveTo(11.8 * o, 3.6 * o),
          e.lineTo(12.4 * o, 4.6 * o),
          e.lineTo(12.8 * o, 3.6 * o),
          e.closePath(),
          e.fill(),
          (e.fillStyle = m),
          e.beginPath(),
          e.moveTo(6 * o, -2 * o),
          e.lineTo(8.5 * o, -5 * o),
          e.lineTo(10.5 * o, -1 * o),
          e.closePath(),
          e.fill(),
          (e.fillStyle = "#f43f5e"),
          e.beginPath(),
          e.moveTo(7 * o, -2 * o),
          e.lineTo(8.5 * o, -4.2 * o),
          e.lineTo(9.8 * o, -1.2 * o),
          e.closePath(),
          e.fill(),
          (e.strokeStyle = `rgba(15, 23, 42, ${u})`),
          (e.lineWidth = 1.4 * o),
          e.beginPath(),
          e.moveTo(8.2 * o, -0.5 * o),
          e.lineTo(10.2 * o, 1.5 * o),
          e.moveTo(10.2 * o, -0.5 * o),
          e.lineTo(8.2 * o, 1.5 * o),
          e.stroke());
    },
    // Icone (antigo db)
    icon: function (e, t, l) {
    const o = l.color || "#475569",
      u = "#334155",
      m = "#e2e8f0",
      c = "#cbd5e1";
    ((e.fillStyle = "rgba(15, 23, 42, 0.35)"),
      e.beginPath(),
      e.ellipse(0, 4.5 * t, 10 * t, 3.5 * t, 0, 0, Math.PI * 2),
      e.fill(),
      (e.strokeStyle = o),
      (e.lineWidth = 3.2 * t),
      (e.lineCap = "round"),
      e.beginPath(),
      e.moveTo(-5 * t, 0),
      e.quadraticCurveTo(-9 * t, -4 * t, -7.5 * t, -7 * t),
      e.stroke(),
      (e.strokeStyle = c),
      (e.lineWidth = 2 * t),
      e.beginPath(),
      e.moveTo(-8.5 * t, -5 * t),
      e.lineTo(-7.5 * t, -7 * t),
      e.stroke(),
      (e.fillStyle = u),
      e.fillRect(-3.5 * t, 1 * t, 2 * t, 4 * t),
      e.fillRect(4 * t, 1 * t, 2 * t, 4 * t),
      (e.fillStyle = o),
      e.fillRect(-5 * t, 1 * t, 2.2 * t, 4.5 * t),
      e.fillRect(2.2 * t, 1 * t, 2.2 * t, 4.5 * t),
      (e.fillStyle = "#0f172a"),
      e.fillRect(-5 * t, 5 * t, 2.2 * t, 0.8 * t),
      e.fillRect(2.2 * t, 5 * t, 2.2 * t, 0.8 * t),
      (e.fillStyle = o),
      e.beginPath(),
      e.moveTo(-5.5 * t, -1 * t),
      e.quadraticCurveTo(-1 * t, -3.8 * t, 3.5 * t, -3 * t),
      e.quadraticCurveTo(5 * t, 0, 2.5 * t, 2 * t),
      e.quadraticCurveTo(-1 * t, 1 * t, -5 * t, 1.5 * t),
      e.closePath(),
      e.fill(),
      (e.fillStyle = m),
      e.beginPath(),
      e.ellipse(1 * t, 0.5 * t, 3.5 * t, 1.8 * t, 0.1, 0, Math.PI * 2),
      e.fill(),
      (e.fillStyle = c),
      e.beginPath(),
      e.moveTo(3 * t, -2.5 * t),
      e.lineTo(5.5 * t, -0.5 * t),
      e.lineTo(4 * t, 0.8 * t),
      e.lineTo(5.8 * t, 1.8 * t),
      e.lineTo(3.2 * t, 2.2 * t),
      e.closePath(),
      e.fill(),
      (e.fillStyle = o),
      e.beginPath(),
      e.ellipse(4.5 * t, -2.5 * t, 3.8 * t, 3.2 * t, 0.2, 0, Math.PI * 2),
      e.fill(),
      e.beginPath(),
      e.moveTo(4 * t, -3 * t),
      e.lineTo(8.5 * t, -1.8 * t),
      e.lineTo(8 * t, 0.6 * t),
      e.lineTo(4 * t, 0.5 * t),
      e.closePath(),
      e.fill(),
      (e.fillStyle = m),
      e.beginPath(),
      e.moveTo(4.5 * t, 0),
      e.lineTo(7.5 * t, 0.2 * t),
      e.lineTo(7 * t, 1.1 * t),
      e.lineTo(4.5 * t, 1 * t),
      e.closePath(),
      e.fill(),
      (e.fillStyle = "#0f172a"),
      e.beginPath(),
      e.roundRect(8 * t, -2.2 * t, 1.4 * t, 1.6 * t, 0.3 * t),
      e.fill(),
      (e.fillStyle = "#ffffff"),
      e.beginPath(),
      e.moveTo(6.8 * t, 0.2 * t),
      e.lineTo(7.3 * t, 1.4 * t),
      e.lineTo(7.7 * t, 0.2 * t),
      e.closePath(),
      e.fill(),
      (e.fillStyle = u),
      e.beginPath(),
      e.moveTo(2 * t, -4.5 * t),
      e.lineTo(2.5 * t, -8.5 * t),
      e.lineTo(4.2 * t, -4.5 * t),
      e.closePath(),
      e.fill(),
      (e.fillStyle = o),
      e.beginPath(),
      e.moveTo(3.2 * t, -4.5 * t),
      e.lineTo(4.2 * t, -8.8 * t),
      e.lineTo(5.8 * t, -4.5 * t),
      e.closePath(),
      e.fill(),
      (e.fillStyle = "#f43f5e"),
      e.beginPath(),
      e.moveTo(3.8 * t, -5 * t),
      e.lineTo(4.3 * t, -7.8 * t),
      e.lineTo(5.2 * t, -5 * t),
      e.closePath(),
      e.fill(),
      (e.fillStyle = "#0f172a"),
      e.beginPath(),
      e.ellipse(4.8 * t, -3.2 * t, 1.4 * t, 1.1 * t, 0.1, 0, Math.PI * 2),
      e.fill(),
      (e.fillStyle = "#fbbf24"),
      e.beginPath(),
      e.arc(5 * t, -3.2 * t, 1 * t, 0, Math.PI * 2),
      e.fill(),
      (e.fillStyle = "#0f172a"),
      e.beginPath(),
      e.ellipse(5.2 * t, -3.2 * t, 0.4 * t, 0.8 * t, 0, 0, Math.PI * 2),
      e.fill(),
      (e.fillStyle = "#ffffff"),
      e.beginPath(),
      e.arc(4.8 * t, -3.5 * t, 0.35 * t, 0, Math.PI * 2),
      e.fill());
  
    },
  },
};
